# Generated by Django 5.1.13 on 2025-11-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_departure', models.TimeField(blank=True, null=True)),
                ('station_departure', models.TimeField(blank=True, null=True)),
                ('campus_arrival', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_saturday', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bus')),
            ],
        ),
    ]
