# Generated by Django 5.1.13 on 2025-11-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busschedule',
            name='direction',
        ),
    ]
