# Generated by Django 5.1.13 on 2025-11-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_bus_profile_bus_stop'),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='BusStop',
        ),
        migrations.RenameField(
            model_name='busschedule',
            old_name='bus',
            new_name='bus_stop',
        ),
    ]
