# Generated by Django 5.1.13 on 2025-11-27 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_room_schoolperiod_busschedule_campus_arrival_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user can access teacher-only features.', verbose_name='teacher status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bus_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.busstop'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1組'), (2, '2組'), (3, '3組'), (4, '4組')], null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.college'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], null=True, verbose_name='grade'),
        ),
    ]
