# Generated by Django 5.1.13 on 2025-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_number',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1組'), (2, '2組'), (3, '3組'), (4, '4組')], null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], null=True, verbose_name='grade'),
        ),
    ]
