# Generated by Django 5.1.13 on 2025-11-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_bus_remove_customuser_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bus',
            new_name='bus_stop',
        ),
    ]
