# Generated by Django 5.1.13 on 2025-10-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hachiouji', '八王子'), ('minamino', '八王子みなみ野')], default='hachiouji', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bus'),
        ),
    ]
