# Generated by Django 5.1.13 on 2025-11-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('sender', models.EmailField(max_length=254, verbose_name='送信元メールアドレス')),
                ('body', models.TextField(verbose_name='本文')),
                ('message_uid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IMAP UID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='受信日時')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
            ],
        ),
    ]
