# Generated by Django 5.1.13 on 2025-12-15 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hachiouji', '八王子'), ('minamino', '八王子みなみ野')], default='hachiouji', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('message_uid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='教室名')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField(unique=True, verbose_name='時限')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
            ],
            options={
                'verbose_name': '時限',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_departure', models.TimeField(blank=True, null=True)),
                ('campus_arrival', models.TimeField(blank=True, null=True)),
                ('station_departure', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_saturday', models.BooleanField(default=False)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_schedules', to='core.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_grade', models.PositiveIntegerField(default=4)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金')], verbose_name='曜日')),
                ('start_period', models.PositiveIntegerField(verbose_name='開始時限')),
                ('end_period', models.PositiveIntegerField(verbose_name='終了時限')),
                ('subject', models.CharField(max_length=100, verbose_name='科目名')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='休講フラグ')),
                ('target_grade', models.PositiveIntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')])),
                ('target_class_number', models.PositiveIntegerField(choices=[(1, '1組'), (2, '2組'), (3, '3組'), (4, '4組')])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_schedules', to='core.course', verbose_name='コース/専攻')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_schedules', to='core.department', verbose_name='学科')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_lectures', to=settings.AUTH_USER_MODEL, verbose_name='担当教師')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_schedules', to='core.room', verbose_name='教室')),
            ],
            options={
                'verbose_name': '時間割',
                'ordering': ['weekday', 'start_period'],
                'constraints': [models.UniqueConstraint(fields=('department', 'course', 'target_grade', 'target_class_number', 'weekday', 'start_period'), name='unique_lecture_slot_for_target')],
            },
        ),
    ]
