# Generated by Django 5.1.13 on 2025-11-21 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.AddField(
            model_name='busschedule',
            name='campus_arrival',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_period', models.IntegerField()),
                ('end_period', models.IntegerField()),
                ('day_of_week', models.CharField(choices=[('mon', '月'), ('tue', '火'), ('wed', '水'), ('thu', '木'), ('fri', '金')], max_length=10)),
                ('is_canceled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_schedules', to='core.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_schedules', to='core.room')),
            ],
        ),
    ]
