# Generated by Django 5.1.13 on 2025-12-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureschedule',
            options={'ordering': ['weekday', 'start_period__period'], 'verbose_name': '時間割', 'verbose_name_plural': '時間割'},
        ),
        migrations.AlterModelOptions(
            name='schoolperiod',
            options={'ordering': ['period'], 'verbose_name': '時限', 'verbose_name_plural': '時限'},
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='end_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_end_set', to='core.schoolperiod', verbose_name='終了時限'),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='start_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_start_set', to='core.schoolperiod', verbose_name='開始時限'),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='target_class_number',
            field=models.PositiveIntegerField(choices=[(1, '1組'), (2, '2組'), (3, '3組'), (4, '4組')], verbose_name='対象クラス'),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='target_grade',
            field=models.PositiveIntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], verbose_name='対象学年'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='教室名'),
        ),
    ]
