# Generated by Django 5.1.13 on 2025-12-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lectureschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureschedule',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '通常'), (1, '休講'), (2, '補講')], default=0, verbose_name='講義状態'),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='target_class_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1組'), (2, '2組'), (3, '3組'), (4, '4組')], verbose_name='対象クラス'),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='target_grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], verbose_name='対象学年'),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金')], verbose_name='曜日'),
        ),
    ]
