# Generated by Django 5.1.13 on 2025-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_schoolperiod_busschedule_campus_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='max_grade',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='end_period',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='start_period',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='period',
            field=models.PositiveIntegerField(),
        ),
    ]
