# Generated by Django 5.1.13 on 2025-11-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_max_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedemail',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
