# Generated by Django 5.1.13 on 2025-12-12 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_receivedemail_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureschedule',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_schedules', to='core.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='target_class_number',
            field=models.PositiveIntegerField(choices=[(1, '1組'), (2, '2組'), (3, '3組'), (4, '4組')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='target_grade',
            field=models.PositiveIntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_schedules', to='core.course'),
        ),
    ]
