# Generated by Django 5.1.13 on 2025-12-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
