# Generated by Django 5.1.13 on 2025-12-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedemail',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.department', verbose_name='対象学科'),
        ),
    ]
