# Generated by Django 5.1.13 on 2025-12-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_receivedemail_target_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedemail',
            name='target_grade',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], null=True, verbose_name='対象学年'),
        ),
    ]
