# Generated by Django 5.1.13 on 2025-12-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_receivedemail_target_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日')], verbose_name='曜日'),
        ),
    ]
