# Generated by Django 5.1.13 on 2026-01-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lectureschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureschedule',
            name='teacher',
            field=models.CharField(blank=True, null=True, verbose_name='担当教員'),
        ),
    ]
