# Generated by Django 5.1.13 on 2026-01-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_content',
            field=models.CharField(choices=[('login', 'ログイン時表示'), ('logout', 'ログアウト時表示')], db_index=True, default='login', max_length=10),
        ),
    ]
