# Generated by Django 5.1.13 on 2026-01-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_display_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='display_content',
        ),
        migrations.AddField(
            model_name='event',
            name='is_external',
            field=models.BooleanField(db_index=True, default=False, help_text='学外向けイベントかどうか（False=学内向け）'),
        ),
    ]
