# Generated by Django 5.1.13 on 2026-01-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_event_display_content_event_is_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
