# Generated by Django 5.1.13 on 2026-01-16 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_event_target_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_grade',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], default=None, null=True),
        ),
    ]
