# Generated by Django 5.1.13 on 2026-01-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_event_target_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'end_date']},
        ),
    ]
