# Generated by Django 5.1.13 on 2026-01-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['is_external', 'start_date', 'end_date']},
        ),
    ]
