# Generated by Django 5.1.13 on 2026-01-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureschedule',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '通常'), (1, '休講')], default=0, verbose_name='講義状態'),
        ),
    ]
