# Generated by Django 5.1.13 on 2026-01-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_lectureschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureschedule',
            name='specific_date',
            field=models.DateField(blank=True, help_text='特定の日のみ休講・補講にする場合に入力します', null=True, verbose_name='特定適用日'),
        ),
    ]
