# Generated by Django 5.1.13 on 2026-01-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_lectureschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureschedule',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='休講日（1日限定）'),
        ),
    ]
