# Generated by Django 5.1.13 on 2026-01-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lectureschedule_canceled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureschedule',
            name='canceled_date',
        ),
    ]
