# Generated by Django 5.1.13 on 2026-01-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lectureschedule_specific_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lectureschedule',
            name='unique_lecture_slot_for_target',
        ),
        migrations.AddConstraint(
            model_name='lectureschedule',
            constraint=models.UniqueConstraint(fields=('department', 'course', 'target_grade', 'target_class_number', 'weekday', 'start_period', 'specific_date'), name='unique_lecture_slot_for_target'),
        ),
    ]
