# Generated by Django 5.1.13 on 2026-01-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_lectureschedule_canceled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='target_department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_grade',
        ),
    ]
