# Generated by Django 5.1.13 on 2026-01-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_lectureschedule_unique_lecture_slot_for_target_and_more'),
        ('core', '0022_remove_event_target_department_and_more'),
    ]

    operations = [
    ]
