# Generated by Django 5.1.13 on 2026-01-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20260126_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveConstraint(
            model_name='lectureschedule',
            name='unique_lecture_slot_for_target',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_external',
        ),
        migrations.RemoveField(
            model_name='lectureschedule',
            name='specific_date',
        ),
        migrations.AddField(
            model_name='event',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_grade',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], null=True),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='休講日'),
        ),
        migrations.AddConstraint(
            model_name='lectureschedule',
            constraint=models.UniqueConstraint(fields=('department', 'course', 'target_grade', 'target_class_number', 'weekday', 'start_period', 'canceled_date'), name='unique_lecture_slot_for_target'),
        ),
    ]
