# Generated by Django 5.1.13 on 2026-01-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'end_date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_grade',
        ),
    ]
