# Generated by Django 5.1.13 on 2025-11-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='max_grade',
        ),
        migrations.AddField(
            model_name='department',
            name='max_grade',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
